variable "Name"{}
variable "Created_by"{}
variable  "Dev"{}
variable "Env"{}
variable "vpc"{}
variable "ami"{}
variable "instance_type"{}
variable "user"{}
variable "zone_id"{}
variable "domain"{}
variable "record"{}
